### ISSUE TITLE
Right side of rudder has wrong texture

### ISSUE THREAD

**Issue by viktorradnai** [viktorradnai/flightgear-ask21#113]
Please see screenshot, the rudder is using the wrong part of the texture.
![fgfs-screen-303](https://cloud.githubusercontent.com/assets/4738178/24086466/c01e92d2-0d07-11e7-9e69-a3acb44ebdfb.png)
![fgfs-screen-304](https://cloud.githubusercontent.com/assets/4738178/24086467/c7f9f83e-0d07-11e7-95a3-0e14139eadee.png)

**Comment by gilbertohasnofb** [comment]
This has to do with UV-mapping, so @D-ECHO could you please take a look at it when you have time?

**Comment by ghost** [comment]
Fixed in #114

**Comment by ghost** [comment]
Closed through #114

**Comment by viktorradnai** [comment]
Hi there, looks like this issue is back on the master branch. Could you please fix it again?

**Comment by ghost** [comment]
will have a look once I'm back from Holidays



------------------------------------------------------------------------
Gesendet mit der Telekom Mail App
<http://www.t-online.de/service/redir/email_app_android_sendmail_footer.htm>


--- Original-Nachricht ---
Von: Viktor Radnai
Betreff: Re: [viktorradnai/flightgear-ask21] Right side of rudder has wrong 
texture (#113)
Datum: 22.08.2017, 2:47 Uhr
An: viktorradnai/flightgear-ask21
Cc: D-ECHO, State change



Hi there, looks like this issue is back on the master branch. Could you 
please fix it again?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/viktorradnai/flightgear-ask21/issues/113#issuecomment-323888188> 
, or mute the thread

**Comment by viktorradnai** [comment]
Closed by #156
